<?php
namespace Masthowasli\Component\FeatureToggle\Tests;

use \Masthowasli\Component\FeatureToggle\Feature;

/**
 * Test class for Feature.
 * Generated by PHPUnit on 2013-04-04 at 16:27:27.
 */
class FeatureTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var string
     */
    protected $defaultName = 'test-feature';

    /**
     * @var Feature
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Feature($this->defaultName);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * Tests initial state of a new feature
     *
     * @covers \Masthowasli\Component\FeatureToggle\Feature::__construct()
     */
    public function testConstructor()
    {
        $this->assertEquals($this->defaultName, $this->object->getName());
        $this->assertAttributeNotEquals(null, 'requirements', $this->object);
        $this->assertAttributeInstanceOf('\Masthowasli\Component\FeatureToggle\Requirement\Collection', 'requirements', $this->object);
    }
}