<?php
/**
 * File of the timed feature tests
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * PHP version 5.3
 *
 * @category   Masthowasli
 * @package    FeatureToggle
 * @subpackage Tests
 * @author     Thomas Sliwa <ts@unfinished.dyndns.org>
 * @copyright  2012-2013 - Thomas Sliwa
 * @license    http://opensource.org/licenses/MIT MIT
 * @link       https://github.com/masthowasli/FeatureToggle
 */

namespace Masthowasli\Component\FeatureToggle\Tests\Feature;

use Masthowasli\Component\FeatureToggle\Feature\Timed;
use Masthowasli\Component\FeatureToggle\Feature\FeatureInterface;
use Masthowasli\Component\FeatureToggle\Feature\Timed\Period;

/**
 * Test class for Feature.
 * Generated by PHPUnit on 2013-04-04 at 16:27:27.
 */
class TimedTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var string
     */
    protected $defaultName = 'test-timed-feature';

    /**
     * @var Period
     */
    protected $activePeriod;

    /**
     * @var Timed
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->activePeriod = new Period(
            new \DateTime('1990-01-01'),
            new \DateTime()
        );

        $this->object = new Timed(
            $this->defaultName,
            $this->activePeriod
        );
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * Tests initial state of a new feature
     *
     * @covers \Masthowasli\Component\FeatureToggle\Feature\Timed::__construct()
     */
    public function testConstructor()
    {
        $this->assertEquals($this->defaultName, $this->object->getName());
        $this->assertAttributeNotEquals(null, 'requirements', $this->object);
        $this->assertAttributeInstanceOf(
            '\Masthowasli\Component\FeatureToggle\Requirement\Collection',
            'requirements',
            $this->object
        );
        $stateProperty = new \ReflectionProperty(
            'Masthowasli\Component\FeatureToggle\Feature\Timed',
            'state'
        );
        $stateProperty->setAccessible(true);

        $this->assertInstanceOf(
            'Masthowasli\Component\FeatureToggle\Feature\FeatureState',
            $stateProperty->getValue($this->object)
        );
    }

    public function testIsEnabled()
    {
        $this->assertTrue($this->object->isEnabled());
    }

    public function testName()
    {
        $this->assertEquals($this->defaultName, $this->object->getName());
    }
}
