<?php
/**
 * File of the Requirement tests
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * PHP version 5.3
 *
 * @category   Masthowasli
 * @package    FeatureToggle
 * @subpackage Tests
 * @author     Thomas Sliwa <ts@unfinished.dyndns.org>
 * @copyright  2012-2014 - Thomas Sliwa
 * @license    http://opensource.org/licenses/MIT MIT
 * @link       https://github.com/masthowasli/FeatureToggle
 */

namespace Masthowasli\Component\FeatureToggle\Tests\Requirement;

use Masthowasli\Component\FeatureToggle\Feature;
use Masthowasli\Component\FeatureToggle\Requirement\Requirement;

/**
 * Test class for Requirement.
 * Generated by PHPUnit on 2013-04-15 at 08:42:19.
 */
class RequirementTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var \Masthowasli\Component\FeatureToggle\Feature
     */
    protected $feature;

    /**
     * @var Requirement
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->feature = new Feature\Toggled('foo');
        $this->object = new Requirement($this->feature);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * Tests initial state of a new requirement
     *
     * @covers Masthowasli\Component\FeatureToggle\Requirement\Requirement::__construct()
     */
    public function testDefaultConstructor()
    {
        $this->assertAttributeInstanceOf(
                '\Masthowasli\Component\FeatureToggle\Feature\FeatureInterface',
                'feature',
                $this->object
        );
        $this->assertEquals(
                Requirement::FEATURE_ENABLED,
                $this->object->getRequiredState()
        );
    }

    /**
     * Tests the get required state of a requirement method
     *
     * @covers Masthowasli\Component\FeatureToggle\Requirement\Requirement::getRequiredState()
     */
    public function testGetRequiredState()
    {
        $this->assertEquals(
                Requirement::FEATURE_ENABLED,
                $this->object->getRequiredState()
        );
    }

    /**
     * Tests the successful set required state of a requirement method invocation
     *
     * @covers Masthowasli\Component\FeatureToggle\Requirement\Requirement::setRequiredState()
     *
     * @depends Masthowasli\Component\FeatureToggle\Tests\Requirement\RequirementTest::testDefaultConstructor
     */
    public function testSetRequiredStateValid()
    {
        $this->object->setRequiredState(Requirement::FEATURE_DISABLED);
        $this->assertEquals(
                Requirement::FEATURE_DISABLED,
                $this->object->getRequiredState()
        );
        $this->object->setRequiredState(Requirement::FEATURE_ENABLED);
        $this->assertEquals(
                Requirement::FEATURE_ENABLED,
                $this->object->getRequiredState()
        );
    }

    /**
     * Tests the not successful set required state of a requirement method invocation
     *
     * @covers Masthowasli\Component\FeatureToggle\Requirement\Requirement::setRequiredState()
     *
     * @depends Masthowasli\Component\FeatureToggle\Tests\Requirement\RequirementTest::testDefaultConstructor
     */
    public function testSetRequiredStateNotValid()
    {
        $this->setExpectedException(
                '\Masthowasli\Component\FeatureToggle\Exception\Requirement'
        );
        $this->object->setRequiredState('somthing');
        $this->setExpectedException(
                '\Masthowasli\Component\FeatureToggle\Exception\Requirement'
        );
        $this->object->setRequiredState(68); // Jaromir Jagr, hockey god
    }
}
